# Generated by Django 5.2.14 on 2026-05-27 00:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('page_reference', models.CharField(blank=True, max_length=100)),
                ('knowledge_type', models.CharField(choices=[('principle', 'Principle'), ('formula', 'Formula'), ('process', 'Process'), ('risk', 'Risk'), ('best_practice', 'Best Practice'), ('warning_sign', 'Warning Sign'), ('methodology', 'Methodology'), ('checklist', 'Checklist'), ('case_insight', 'Case Insight'), ('decision_rule', 'Decision Rule'), ('example', 'Example'), ('definition', 'Definition'), ('framework', 'Framework'), ('lesson_learned', 'Lesson Learned'), ('other', 'Other')], default='other', max_length=30)),
                ('executive_insight', models.TextField(blank=True)),
                ('detailed_explanation', models.TextField(blank=True)),
                ('practical_application', models.TextField(blank=True)),
                ('consultant_use_case', models.TextField(blank=True)),
                ('course_use_case', models.TextField(blank=True)),
                ('common_mistakes', models.TextField(blank=True)),
                ('warning_signs', models.TextField(blank=True)),
                ('best_practices', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('personal_commentary', models.TextField(blank=True)),
                ('real_world_applicability', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('consulting_value', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('teaching_value', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('ai_extracted', 'AI Extracted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('source_quote_short', models.TextField(blank=True)),
                ('citation', models.TextField(blank=True)),
                ('would_i_use_this', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_units', to='library.chapter')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_units', to='taxonomy.concept')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_units', to='taxonomy.domain')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_units', to='library.source')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_units', to='taxonomy.subdomain')),
                ('tags', models.ManyToManyField(blank=True, related_name='knowledge_units', to='taxonomy.tag')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_units', to='taxonomy.topic')),
            ],
            options={
                'verbose_name': 'Knowledge Unit',
                'verbose_name_plural': 'Knowledge Units',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('related_to', 'Related To'), ('supports', 'Supports'), ('contradicts', 'Contradicts'), ('example_of', 'Example Of'), ('prerequisite_of', 'Prerequisite Of'), ('expands_on', 'Expands On'), ('risk_of', 'Risk Of')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('from_knowledge_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge.knowledgeunit')),
                ('to_knowledge_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge.knowledgeunit')),
            ],
            options={
                'verbose_name': 'Knowledge Relationship',
                'verbose_name_plural': 'Knowledge Relationships',
                'ordering': ['-created_at'],
            },
        ),
    ]
