# Generated by Django 5.2.14 on 2026-05-27 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeunit',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='confidence_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='duplicate_group',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='governance_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('archived', 'Archived')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='source_quality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
