# Generated by Django 5.2.14 on 2026-05-27 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_extraction', '0003_documentingestionjob_textchunk'),
        ('knowledge', '0002_knowledgeunit_approval_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeunit',
            name='imported_from_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_knowledge_units', to='ai_extraction.extractionbatch'),
        ),
        migrations.AddField(
            model_name='knowledgeunit',
            name='imported_via',
            field=models.CharField(blank=True, choices=[('candidate_review', 'Candidate Review'), ('fast_import', 'Fast Import')], max_length=30),
        ),
    ]
