# Generated by Django 5.2.14 on 2026-05-27 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('library', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('input_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_ai', 'Ready for AI'), ('ai_output_received', 'AI Output Received'), ('parsed', 'Parsed'), ('imported', 'Imported'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('ai_output_raw', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_batches', to='library.chapter')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_batches', to='library.source')),
            ],
            options={
                'verbose_name_plural': 'extraction batches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('proposed_knowledge_type', models.CharField(blank=True, choices=[('principle', 'Principle'), ('formula', 'Formula'), ('process', 'Process'), ('risk', 'Risk'), ('best_practice', 'Best Practice'), ('warning_sign', 'Warning Sign'), ('methodology', 'Methodology'), ('checklist', 'Checklist'), ('case_insight', 'Case Insight'), ('decision_rule', 'Decision Rule'), ('example', 'Example'), ('definition', 'Definition'), ('framework', 'Framework'), ('lesson_learned', 'Lesson Learned'), ('other', 'Other')], max_length=30)),
                ('executive_insight', models.TextField(blank=True)),
                ('detailed_explanation', models.TextField(blank=True)),
                ('practical_application', models.TextField(blank=True)),
                ('consultant_use_case', models.TextField(blank=True)),
                ('course_use_case', models.TextField(blank=True)),
                ('common_mistakes', models.TextField(blank=True)),
                ('warning_signs', models.TextField(blank=True)),
                ('best_practices', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('citation', models.TextField(blank=True)),
                ('source_quote_short', models.TextField(blank=True)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ai_extraction.extractionbatch')),
                ('imported_knowledge_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_candidates', to='knowledge.knowledgeunit')),
                ('proposed_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_candidates', to='taxonomy.concept')),
                ('proposed_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_candidates', to='taxonomy.domain')),
                ('proposed_subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_candidates', to='taxonomy.subdomain')),
                ('proposed_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_candidates', to='taxonomy.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prompt_text', models.TextField()),
                ('output_format_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to='taxonomy.domain')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='prompt_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ai_extraction.extractionprompttemplate'),
        ),
    ]
