# Generated by Django 5.2.14 on 2026-05-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_extraction', '0001_initial'),
        ('knowledge', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatch',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='extractioncandidate',
            constraint=models.UniqueConstraint(fields=('batch', 'title'), name='unique_candidate_title_per_batch'),
        ),
    ]
