# Generated by Django 5.2.14 on 2026-05-27 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_extraction', '0002_extractionbatch_parse_error_and_more'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, upload_to='ingestion/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('extraction_method', models.CharField(choices=[('pypdf', 'PDF (pypdf)'), ('manual_text', 'Manual text')], default='pypdf', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='library.source')),
            ],
            options={
                'verbose_name': 'document ingestion job',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('chunk_number', models.PositiveIntegerField()),
                ('start_page', models.PositiveIntegerField(blank=True, null=True)),
                ('end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_chunks', to='library.chapter')),
                ('created_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_chunks', to='ai_extraction.extractionbatch')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_extraction.documentingestionjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_chunks', to='library.source')),
            ],
            options={
                'ordering': ['ingestion_job', 'chunk_number'],
                'unique_together': {('ingestion_job', 'chunk_number')},
            },
        ),
    ]
