# Generated by Django 5.2.14 on 2026-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_extraction', '0003_documentingestionjob_textchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='avoid_generic_filler',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='extraction_style',
            field=models.CharField(choices=[('general', 'General'), ('consultant', 'Consultant'), ('academic', 'Academic'), ('course_creation', 'Course Creation'), ('executive_summary', 'Executive Summary'), ('claims_analysis', 'Claims Analysis'), ('contract_analysis', 'Contract Analysis'), ('project_controls', 'Project Controls'), ('operational_lessons', 'Operational Lessons'), ('checklist_generation', 'Checklist Generation')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='minimum_quality_threshold',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_best_practices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_common_mistakes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_consultant_use_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_course_use_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_page_references',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_practical_application',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_source_traceability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='require_warning_signs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionprompttemplate',
            name='target_granularity',
            field=models.CharField(choices=[('high_level', 'High Level'), ('medium', 'Medium'), ('atomic', 'Atomic')], default='medium', max_length=20),
        ),
    ]
